### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute 'split'

### ISSUE THREAD

**Issue by Erlemar** [FooSoft/yomichan#13]
Hello again!

I have a new problem:
when I try to see definitions of certain kanji, for example when I put mouse on 刹 in 刹那的 I receive the following error.

Traceback (most recent call last):
  File "C:\Users\Andrey\Documents\Anki\addons\yomi_base\reader.py", line 336, in onContentMousePress
    self.updateSampleMouseEvent(event)
  File "C:\Users\Andrey\Documents\Anki\addons\yomi_base\reader.py", line 487, in updateSampleMouseEvent
    self.updateSampleFromPosition()
  File "C:\Users\Andrey\Documents\Anki\addons\yomi_base\reader.py", line 519, in updateSampleFromPosition
    self.state.kanjiDefs = self.language.findKanji(contentSampleFlat[:lengthMatched])
  File "C:\Users\Andrey\Documents\Anki\addons\yomi_base\japanese\translate.py", line 69, in findKanji
    match = self.dictionary.findKanji(c)
  File "C:\Users\Andrey\Documents\Anki\addons\yomi_base\japanese\dictionary.py", line 87, in findKanji
    'kunyomi':   kunyomi.split(),
AttributeError: 'NoneType' object has no attribute 'split'

This happens in Desktop version on Windows 10.

**Comment by FooSoft** [comment]
Yikes! I missed this when switching dictionary formats. Should be fixed now if you update to 0.21b

**Comment by Erlemar** [comment]
Thank you! The problem is fixed now.
