### ISSUE TITLE
Error when enabling Anki Integration

### ISSUE THREAD

**Issue by fadelesskekse** [FooSoft/yomichan#1880]
Hello, I just recently installed Ankiconnect on Anki and am attempting to get yomichan connected with it.
When I go to :  http://127.0.0.1:8765, it works.
I do not know what other information to post but I will try to post whatever you ask for to figure this issue out.

Thank you for your time,
Dakota

{
    "action": "deckNames",
    "status": 200,
    "apiError": "collection is not available"
}

Error: Anki error: collection is not available
    at AnkiConnect._invoke (chrome-extension://ogmnaimimemjmbakcfefmnahgdfhfami/js/comm/anki.js:207:31)
    at async AnkiConnect.getDeckNames (chrome-extension://ogmnaimimemjmbakcfefmnahgdfhfami/js/comm/anki.js:83:16)
    at async AnkiController._getDeckNames (chrome-extension://ogmnaimimemjmbakcfefmnahgdfhfami/js/pages/settings/anki-controller.js:276:28)

**Comment by toasted-nutbread** [comment]
Can you screenshot what your Anki window looks like when you encounter this issue?
