### ISSUE TITLE
Dev build 20.8.23.0 crashes in Microsoft Edge inPrivate mode

### ISSUE THREAD

**Issue by paperclip-dayo** [FooSoft/yomichan#754]
Edge ver: 86.0.618.0 (Canary channel)
Yomichan: 20.8.23.0_dev (enabled to work in inPrivate)

Trying to scan a word in inPrivate mode "crashes" Yomichan (red pause icon) and throws following errors in dev console:

```
>Yomichan (development build) v20.8.23.0 has encountered a problem.
Originating URL: undefined
SecurityError: Failed to read the 'sessionStorage' property from 'Window': Access is denied for this document.
Error: Failed to read the 'sessionStorage' property from 'Window': Access is denied for this document.
    at DisplayFloat._updateMode (chrome-extension://bcknnfebhefllbjhagijobjklocakpdm/mixed/js/display.js:1322:22)
    at DisplayFloat.prepare (chrome-extension://bcknnfebhefllbjhagijobjklocakpdm/mixed/js/display.js:160:14)
    at DisplayFloat.prepare (chrome-extension://bcknnfebhefllbjhagijobjklocakpdm/fg/js/float.js:44:21)
    at chrome-extension://bcknnfebhefllbjhagijobjklocakpdm/fg/js/float-main.js:29:23

>Yomichan (development build) v20.8.23.0 has encountered a problem.
Originating URL: undefined
Error: Timeout
    at chrome-extension://bcknnfebhefllbjhagijobjklocakpdm/mixed/js/frame-client.js:150:24
```
Yomichan 20.8.3.0 (stable) is not affected by this issue.
Combination of Edge Stable (84.0.522.63) and Yomichan 20.8.23.0_dev also seems to work fine.

**Comment by toasted-nutbread** [comment]
Thanks for the find, I've created a change to fix this. @FooSoft You can probably just deploy a new full build for this, since I haven't made any other changes since.
